### ISSUE TITLE
I can't update master password

### ISSUE THREAD

**Issue by ghostebony** [padloc/padloc#527]
using web app

Uncaught (in promise) Error
    at WebCryptoProvider._decryptAES (crypto.ts:178:19)
    at async Account.getData (container.ts:65:16)
    at async Account.unlock (container.ts:122:13)
    at async Account.setPassword (account.ts:135:9)
    at async app.ts:761:13
    at async App.updateAccount (app.ts:823:9)
    at async App.changePassword (app.ts:759:9)
    at async SettingsSecurity._changePassword (settings-security.ts:126:9)

**Comment by BrunoBernardino** [comment]
@ghostebony is this happening on a self-hosted instance or https://web.padloc.app? If the latter, what is your browser and version?

**Comment by ghostebony** [comment]
on https://web.padloc.app/
using Microsoft Edge: 103.0.1264.77 (Official build) (64-bit)

just checked and I can't change on the android app either
using Android 12, Padloc v4.0.1

**Comment by BrunoBernardino** [comment]
Alright, I can replicate this, will investigate further, thanks for reporting @ghostebony !
