### ISSUE TITLE
Error whilst Building the Padloc Chrome Extension on Ubuntu 22.04 LTS.

### ISSUE THREAD

**Issue by QQTGaming** [padloc/padloc#750]
**Used command:** npm ci && PL_SERVER_URL=https://<working url>/server/ npm run web-extension:build
**OS:** Ubuntu 22.04 LTS

**Done with Root permissions.**

```
lerna ERR! npm run build exited 2 in '@padloc/extension'
lerna ERR! npm run build stdout:

> @padloc/extension@4.3.0 build
> webpack

lerna ERR! npm run build stderr:
[webpack-cli] Failed to load '/root/padloc/packages/extension/webpack.config.js' config
[webpack-cli] /root/padloc/packages/extension/webpack.config.js:93
                            name: web_extension?.name || name,
                                                ^

SyntaxError: Unexpected token '.'
    at new Script (vm.js:88:7)
    at NativeCompileCache._moduleCompile (/root/padloc/packages/extension/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/root/padloc/packages/extension/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (/root/padloc/packages/extension/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at loadConfig (/root/padloc/packages/extension/node_modules/webpack-cli/lib/webpack-cli.js:1327:31)
    at WebpackCLI.resolveConfig (/root/padloc/packages/extension/node_modules/webpack-cli/lib/webpack-cli.js:1459:44)
lerna ERR! npm run build exited 2 in '@padloc/extension'
```

**Comment by giftedl** [comment]
There is multiple things wrong with what your doing:
1. **Never, and I mean never, run build scripts with root permissions**. This applies to everything, not just Padloc. 
2. `npm ci && PL_SERVER_URL=https:///server/ npm run web-extension:build` is not a valid command. Did you mean `npm ci && PL_SERVER_URL=https:///server/ && npm run web-extension:build`

You are most likely running an older version of Padloc, or just not providing all variables.
