### ISSUE TITLE
Error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by floviolleau** [padloc/padloc#760]
Hi,

Thanks for maintaining this project.

I have some error while installing it with a decent recent stack.

```bash
npm run pwa:build

> padloc@4.3.0 pwa:build
> lerna run build --scope @padloc/pwa

lerna notice cli v5.6.2
lerna notice filter including "@padloc/pwa"
lerna info filter [ '@padloc/pwa' ]
lerna info Executing command in 1 package: "npm run build"
lerna ERR! npm run build exited 1 in '@padloc/pwa'
lerna ERR! npm run build stdout:

> @padloc/pwa@4.3.0 build
> webpack

lerna ERR! npm run build stderr:
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (/home/user/padloc/packages/pwa/node_modules/webpack/lib/util/createHash.js:145:18)
    at BulkUpdateDecorator.update (/home/user/padloc/packages/pwa/node_modules/webpack/lib/util/createHash.js:46:50)
    at OriginalSource.updateHash (/home/user/padloc/packages/pwa/node_modules/webpack-sources/lib/OriginalSource.js:138:8)
    at NormalModule._initBuildHash (/home/user/padloc/packages/pwa/node_modules/webpack/lib/NormalModule.js:888:17)
    at handleParseResult (/home/user/padloc/packages/pwa/node_modules/webpack/lib/NormalModule.js:954:10)
    at /home/user/padloc/packages/pwa/node_modules/webpack/lib/NormalModule.js:1048:4
    at processResult (/home/user/padloc/packages/pwa/node_modules/webpack/lib/NormalModule.js:763:11)
    at /home/user/padloc/packages/pwa/node_modules/webpack/lib/NormalModule.js:827:5
/home/user/padloc/packages/pwa/node_modules/loader-runner/lib/LoaderRunner.js:146
		if(isError) throw e;
		            ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (/home/user/padloc/packages/pwa/node_modules/webpack/lib/util/createHash.js:145:18)
    at BulkUpdateDecorator.update (/home/user/padloc/packages/pwa/node_modules/webpack/lib/util/createHash.js:46:50)
    at SourceMapSource.updateHash (/home/user/padloc/packages/pwa/node_modules/webpack-sources/lib/SourceMapSource.js:231:8)
    at NormalModule._initBuildHash (/home/user/padloc/packages/pwa/node_modules/webpack/lib/NormalModule.js:888:17)
    at handleParseResult (/home/user/padloc/packages/pwa/node_modules/webpack/lib/NormalModule.js:954:10)
    at /home/user/padloc/packages/pwa/node_modules/webpack/lib/NormalModule.js:1048:4
    at processResult (/home/user/padloc/packages/pwa/node_modules/webpack/lib/NormalModule.js:763:11)
    at /home/user/padloc/packages/pwa/node_modules/webpack/lib/NormalModule.js:827:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.17.1
lerna ERR! npm run build exited 1 in '@padloc/pwa'
```

I did a `npm audit fix --force` and then re run `npm run pwa:build` same error.

If I do `export NODE_OPTIONS=--openssl-legacy-provider` and then `npm run pwa:build` it works but this can lead to security issues like mentionned here: https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported

Can you please have a look and release a new version ?

Thanks

**Comment by giftedl** [comment]
You must switch to Node.js 16 (`nvm install 16 && nvm use 16` if you have Node Version Manager) as Padloc uses the old crypto API
